server:
  port: 8080

spring:
  application:
    name: my-application
  ai:
    openai:
      api-key: "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"
      model: "gpt-4" # modelo de OpenAI a utilizar
      endpoint: "https://api.openai.com/v1/chat/completions" # endpoint de OpenAI para chat completions
      temperature: 0.7 # nivel de creatividad de las respuestas generadas por el modelo
      max-tokens: 100 # numero maximo de tokens en la respuesta generada por el modelo